name: End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Set Cypress baseUrl from Netlify
        run: echo "export CYPRESS_BASE_URL=$DEPLOY_PREVIEW_URL" >> $GITHUB_ENV

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          config: baseUrl=${{ github.event.inputs.deployPrimeUrl }}
