name: End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6

      - name: Deploy to Netlify
        run: npx netlify-cli deploy --prod
        with:
          config: baseUrl=${{ github.event.inputs.deployPrimeUrl }}
